---
- name: test
  shell:
    cmd:  ifdown eth0 && ifup eth0 

- name: Update apt cache 
  apt: name=haproxy state=present update_cache=yes 

- name: install haproxy
  apt: name=haproxy state=present

- name: Update haproxy config
  template: src=haproxy.cfg
             dest=/etc/haproxy/haproxy.cfg
             #  notify:
#    - restart haproxy

- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes
