---

- name: configure "nfs"
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nfs

- name: Create a directory if it does not exist
  file:
    path: /export/DATA
    state: directory
    mode: '0755'
 

